import logging
import os

from github import Auth, Github, GithubException

logger = logging.getLogger(__name__)


def create_agent_pr(repo_name, branch_name, file_path, content, commit_message):
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        logger.error("GITHUB_TOKEN is not set")
        return False
    g = Github(auth=Auth.Token(token))
    user = g.get_user()
    repo = user.get_repo(repo_name)

    try:
        source = repo.get_branch(repo.default_branch)
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source.commit.sha)

        try:
            contents = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                contents.path,
                commit_message,
                content,
                contents.sha,
                branch=branch_name,
            )
        except GithubException as exc:
            if getattr(exc, "status", None) == 404:
                repo.create_file(file_path, commit_message, content, branch=branch_name)
            else:
                raise

        pr = repo.create_pull(
            title=f"Agent update: {commit_message}",
            body=(
                "This PR was automatically generated by the local "
                "Multi-Repo Agentic Workflow. Please review."
            ),
            head=branch_name,
            base=repo.default_branch,
        )
        logger.info("Successfully opened PR #%s on %s", pr.number, repo_name)
        return True
    except Exception as e:
        logger.error("Failed to create PR: %s", str(e))
        return False
